# Generated by Django 3.0.5 on 2020-05-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0002_auto_20200501_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='world_premiere',
            new_name='date_add',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='poster',
            new_name='view',
        ),
    ]
