# Generated by Django 3.0.5 on 2020-05-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0004_auto_20200507_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
    ]
