# Generated by Django 3.0.5 on 2020-05-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintings', '0005_auto_20200508_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(upload_to='author/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=150, null=True),
        ),
    ]
